In [21]:
import pandas as pd

cctv_sn = pd.read_csv('CCTV현황(제공표준).txt', sep= '\t', encoding= 'utf-8')
cctv_sn

,관리기관명,소재지도로명주소,소재지지번주소,설치목적구분,카메라대수,카메라화소수,촬영방면정보,보관일수,설치연월,관리기관전화번호,위도,경도,데이터기준일자
0,연천군 안전총괄과,NaN,경기도 연천군 백학면 학곡리 33-2,재난재해,2,0,NaN,10,2021-12,031-839-2428,38.0724685938,127.0130218227,2024-07-31
1,연천군 안전총괄과,NaN,경기도 연천군 백학면 노곡리 579-2,재난재해,2,0,NaN,10,2021-12,031-839-2428,37.9831621129,127.0681704349,2024-07-31
2,연천군 안전총괄과,NaN,경기도 연천군 백학면 노곡리 600,재난재해,2,0,NaN,10,2021-12,031-839-2428,37.9853414516,127.0706433030,2024-07-31
3,연천군 안전총괄과,NaN,경기도 연천군 미산면 우정리 105-1,재난재해,2,0,NaN,10,2021-12,031-839-2428,37.9870076406,127.0734281732,2024-07-31
4,연천군 안전총괄과,NaN,경기도 연천군 미산면 동이리 426-1,재난재해,2,0,NaN,10,2021-12,031-839-2428,37.9970981644,127.0755704511,2024-07-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58667,경기도 화성시청,NaN,경기도 화성시 안녕동 164-111,생활방범,1,200,NaN,30,2023-08,031-5189-3528,37.2082,126.9997,2024-07-23
58668,경기도 화성시청,경기도 화성시 봉담읍 상리1길 87,경기도 화성시 상리 716,생활방범,1,200,NaN,30,2020-11,031-5189-3528,37.2249,126.9412,2024-07-23
58669,경기도 화성시청,NaN,경기도 화성시 상리 712-2,생활방범,1,200,NaN,30,2020-11,031-5189-3528,37.2240,126.9441,2024-07-23
58670,경기도 화성시청,NaN,경기도 화성시 석우동 72,생활방범,1,200,NaN,30,2023-09,031-5189-3528,37.2236,127.0745,2024-07-23
58671,경기도 화성시청,NaN,경기도 화성시 석우동 102,생활방범,1,200,NaN,30,2008-01,031-5189-3528,37.2169,127.0786,2024-07-23

In [22]:
import pandas as pd
crime = pd.read_excel('F022602_20250312152046134_excel.xlsx')
crime

C:\Users\jheon\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,통계표명:,범죄유형 및 시도별 범죄율 1),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,단위:,건/10만 명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,...,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,전체,형법범죄,살인,강도,성폭력,폭행·상해,절도,특별법범죄,전체,...,절도,특별법범죄,전체,형법범죄,살인,강도,성폭력,폭행·상해,절도,특별법범죄
3,전국,"3,418.5","2,013.9",1.6,1.6,61.9,391.1,362.9,"1,404.6","3,307.7",...,322.3,"1,186.4","3,050.7","1,944.5",1.4,1.0,80.3,307.1,353.9,"1,106.2"
4,서울,"3,524.1","2,280.8",1.7,1.6,97.0,405.2,438.4,"1,243.3","3,309.7",...,354.0,"1,004.1","3,139.8","2,180.8",1.2,1.3,112.6,331.6,400.5,959.0
5,부산,"3,816.6","2,402.4",2.0,2.5,61.2,445.1,433.7,"1,414.2","3,804.7",...,383.1,"1,260.3","3,580.4","2,344.6",1.6,1.4,85.8,347.1,418.5,"1,235.8"
6,대구,"3,408.3","2,011.1",1.7,1.5,53.0,388.4,381.2,"1,397.2","3,279.8",...,389.9,"1,157.8","3,020.5","1,981.7",1.3,1.4,78.6,317.8,414.9,"1,038.8"
7,인천,"3,440.5","2,155.1",1.7,2.0,71.1,489.3,344.7,"1,285.4","3,264.6",...,278.2,"1,109.1","3,079.8","1,954.8",1.9,1.0,90.1,337.8,300.6,"1,125.0"
8,광주,"3,537.0","2,028.4",1.5,2.0,57.2,435.5,336.0,"1,508.5","3,370.6",...,336.6,"1,270.3","2,935.8","1,818.8",0.2,0.7,72.8,293.1,358.5,"1,117.0"
9,대전,"3,176.7","2,005.3",1.5,1.7,68.1,392.6,391.4,"1,171.4","3,147.7",...,343.6,973.9,"3,102.1","2,241.2",1.4,1.2,94.3,355.7,412.5,861.0
10,울산,"2,251.4","1,145.4",1.5,1.2,29.2,241.2,190.2,"1,106.0","2,187.0",...,187.2,996.4,"1,597.4",840.8,0.8,0.3,30.1,153.3,155.1,756.6
11,세종,"1,902.5","1,215.2",0.9,-,29.6,162.8,256.7,687.3,"1,909.5",...,284.8,607.1,"1,804.5","1,223.5",1.3,0.5,54.6,140.8,290.0,581.0
12,경기,"3,274.7","1,882.5",1.3,1.4,53.3,382.9,317.4,"1,392.2","3,192.6",...,274.8,"1,183.7","2,858.9","1,784.0",1.3,0.9,72.2,293.5,303.9,"1,074.9"
13,강원,"3,513.6","1,900.9",1.5,1.7,56.2,380.8,309.0,"1,612.8","3,392.6",...,276.4,"1,349.6","3,017.1","1,821.2",1.8,1.2,74.2,300.2,303.8,"1,195.9"
14,충북,"3,309.6","1,871.1",2.0,2.2,50.9,331.3,366.9,"1,438.5","3,166.8",...,322.8,"1,205.9","2,896.8","1,841.6",1.8,1.6,70.1,270.2,352.5,"1,055.2"
15,충남,"3,374.1","1,837.8",2.1,1.5,48.1,310.2,377.2,"1,536.3","3,300.8",...,328.5,"1,343.4","3,111.3","1,814.7",2.1,1.1,68.8,243.7,351.5,"1,296.6"
16,전북,"3,217.0","1,751.4",2.4,1.6,52.1,357.3,323.8,"1,465.7","3,112.9",...,312.8,"1,254.2","3,018.5","1,812.3",2.0,0.6,64.8,263.6,317.5,"1,206.2"
17,전남,"3,867.4","1,871.3",1.6,1.5,49.7,405.9,323.8,"1,996.1","3,761.5",...,324.5,"1,619.4","3,479.8","1,846.4",1.8,0.7,63.2,320.4,350.7,"1,633.5"
18,경북,"3,306.2","1,819.3",1.5,1.0,44.4,346.1,332.4,"1,486.9","3,159.8",...,326.2,"1,284.1","3,004.0","1,839.5",1.4,0.7,62.9,280.4,397.8,"1,164.6"
19,경남,"3,701.6","2,107.5",1.7,1.6,47.6,409.7,378.4,"1,594.1","3,694.6",...,380.9,"1,348.1","3,389.4","2,101.4",1.6,1.1,68.8,332.2,403.9,"1,288.0"
20,제주,"4,293.6","2,643.5",3.2,3.2,77.2,494.1,490.6,"1,650.1","4,381.0",...,453.8,"1,376.0","4,066.6","2,819.1",1.9,0.7,93.5,513.5,463.7,"1,247.4"
21,출처:,"검찰청,「범죄분석통계」",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,주석:,"1) 시도별 범죄율 = (시도별 범죄건수 ÷ 시도별 인구) × 100,000. 시도...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
cctv_sn.head()

,관리기관명,소재지도로명주소,소재지지번주소,설치목적구분,카메라대수,카메라화소수,촬영방면정보,보관일수,설치연월,관리기관전화번호,위도,경도,데이터기준일자
0,연천군 안전총괄과,NaN,경기도 연천군 백학면 학곡리 33-2,재난재해,2,0,NaN,10,2021-12,031-839-2428,38.0724685938,127.0130218227,2024-07-31
1,연천군 안전총괄과,NaN,경기도 연천군 백학면 노곡리 579-2,재난재해,2,0,NaN,10,2021-12,031-839-2428,37.9831621129,127.0681704349,2024-07-31
2,연천군 안전총괄과,NaN,경기도 연천군 백학면 노곡리 600,재난재해,2,0,NaN,10,2021-12,031-839-2428,37.9853414516,127.0706433030,2024-07-31
3,연천군 안전총괄과,NaN,경기도 연천군 미산면 우정리 105-1,재난재해,2,0,NaN,10,2021-12,031-839-2428,37.9870076406,127.0734281732,2024-07-31
4,연천군 안전총괄과,NaN,경기도 연천군 미산면 동이리 426-1,재난재해,2,0,NaN,10,2021-12,031-839-2428,37.9970981644,127.0755704511,2024-07-31

In [23]:
cctv_sn.drop(columns=['관리기관명', '소재지도로명주소', '설치목적구분', '카메라화소수', '촬영방면정보', '보관일수'], inplace=True)
cctv_sn

,소재지지번주소,카메라대수,설치연월,관리기관전화번호,위도,경도,데이터기준일자
0,경기도 연천군 백학면 학곡리 33-2,2,2021-12,031-839-2428,38.0724685938,127.0130218227,2024-07-31
1,경기도 연천군 백학면 노곡리 579-2,2,2021-12,031-839-2428,37.9831621129,127.0681704349,2024-07-31
2,경기도 연천군 백학면 노곡리 600,2,2021-12,031-839-2428,37.9853414516,127.0706433030,2024-07-31
3,경기도 연천군 미산면 우정리 105-1,2,2021-12,031-839-2428,37.9870076406,127.0734281732,2024-07-31
4,경기도 연천군 미산면 동이리 426-1,2,2021-12,031-839-2428,37.9970981644,127.0755704511,2024-07-31
...,...,...,...,...,...,...,...
58667,경기도 화성시 안녕동 164-111,1,2023-08,031-5189-3528,37.2082,126.9997,2024-07-23
58668,경기도 화성시 상리 716,1,2020-11,031-5189-3528,37.2249,126.9412,2024-07-23
58669,경기도 화성시 상리 712-2,1,2020-11,031-5189-3528,37.2240,126.9441,2024-07-23
58670,경기도 화성시 석우동 72,1,2023-09,031-5189-3528,37.2236,127.0745,2024-07-23
58671,경기도 화성시 석우동 102,1,2008-01,031-5189-3528,37.2169,127.0786,2024-07-23

In [27]:
regions = [
    "과천시", "광명시", "광주시", "군포시", "김포시", "부천시", "성남시", "수원시", "시흥시", "안산시",
    "안성시", "안양시", "여주시", "오산시", "용인시", "의왕시", "이천시", "평택시", "하남시", "화성시", "양평군"
]

# '주소' 컬럼에서 경기 남부 지역이 포함된 데이터 필터링
pattern = "|".join([f"경기도 {region}" for region in regions])  # "경기도 과천시|경기도 광명시|..."
cctv_sn = cctv_sn[cctv_sn['소재지지번주소'].str.contains(pattern, na=False)]

cctv_sn.to_csv("경기남부_필터링.csv", index=False, encoding='utf-8-sig')

In [18]:
cctv_sn.reset_index(drop=True, inplace=True)
cctv_sn

,소재지지번주소,카메라대수,설치연월,관리기관전화번호,위도,경도,데이터기준일자
0,경기도 성남시 수정구 태평4동 7296-17새마을금고 앞,1,2010-07,031-729-2482,37.44834,127.14188,2022-11-25
1,경기도 성남시 수정구 태평3동 3745-17,1,2009-11,031-729-2482,37.44403,127.13199,2022-11-25
2,경기도 성남시 분당구 삼평동 740번지 봇들교사거리 백범초교앞,1,2011-06,031-729-2482,37.39723,127.11311,2022-11-25
3,경기도 성남시 분당구 삼평동 662번지 봇들교사거리좌측,1,2011-06,031-729-2482,37.39802,127.11152,2022-11-25
4,경기도 성남시 분당구 삼평동 708번지 사송사거리-상,1,2011-06,031-729-2482,37.40393,127.11534,2022-11-25
...,...,...,...,...,...,...,...
2947,경기도 성남시 운중동 1017-4번지,3,2011-06,031-729-2483,37.3902641,127.0837197,2022-11-25
2948,경기도 성남시 운중동 1035-11번지,4,2011-06,031-729-2483,37.3892842,127.0826679,2022-11-25
2949,경기도 성남시 서현2동 340-11번지,3,2017-12,031-729-2483,37.37538,127.14253,2022-11-25
2950,경기도 성남시 서현2동 293번지,4,2018-07,031-729-2483,37.37583,127.13565,2022-11-25
2951,경기도 성남시 서현2동 330-6번지,5,2019-09,031-729-2483,37.37748,127.13997,2022-11-25